import Link from 'next/link'
import { Card } from '@/components/ui'

export default function HomePage() {
  return (
    <main className="min-h-screen bg-zinc-50 px-6 py-16">
      <section className="mx-auto max-w-5xl">
        <p className="text-sm font-semibold uppercase tracking-widest text-zinc-500">Generated by NEXUS OS</p>
        <h1 className="mt-4 max-w-3xl text-5xl font-black tracking-tight text-zinc-950">Creator Sponsor Pipeline</h1>
        <p className="mt-5 max-w-2xl text-lg leading-8 text-zinc-600">
          A production-grade MVP workspace focused on the three highest-value pain points, with a locked roadmap ready for paid expansion.
        </p>
        <div className="mt-8 flex gap-3">
          <Link href="/dashboard" className="inline-flex rounded-lg bg-zinc-900 px-4 py-2 text-sm font-semibold text-white hover:bg-zinc-700">
            Open dashboard
          </Link>
        </div>
        <div className="mt-12 grid gap-4 md:grid-cols-3">
          {['Top 3 pain-point workflows', 'Actionable operating dashboard', 'One-click roadmap unlock'].map(item => (
            <Card key={item}>
              <h2 className="font-bold text-zinc-950">{item}</h2>
              <p className="mt-2 text-sm text-zinc-500">Built to show immediate value now and a clear paid expansion path next.</p>
            </Card>
          ))}
        </div>
      </section>
    </main>
  )
}
